name: Hardhat Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CMC_API_KEY: ${{ secrets.CMC_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install

      - name: Compile Contracts
        run: npx hardhat compile

      - name: Run Tests
        run: npx hardhat test
